import { describe, expect, it } from 'vitest';
import { readFileSync } from 'node:fs';
import path from 'node:path';

describe('blog index page content', () => {
  it('accepts initialPosts and fetches the manifest for an OpenAI-like archive layout', () => {
    const source = readFileSync(path.join(process.cwd(), 'pages', 'BlogIndexPage.tsx'), 'utf8');

    expect(source).toContain('initialPosts');
    expect(source).toContain("/blog_manifest.json");
    expect(source).toContain('applySeoToDocument');
    expect(source).toContain('selectedCategorySlug');
    expect(source).toContain('mobileFiltersOpen');
    expect(source).toContain('Filtrele');
    expect(source).toContain('Tümü');
    expect(source).toContain('All');
    expect(source).toContain('Daha fazla yükle');
    expect(source).toContain('Load more');
    expect(source).toContain('pt-32');
    expect(source).toContain('sm:pt-36');
    expect(source).toContain('lg:pt-40');
    expect(source).toContain('flex flex-col gap-6');
    expect(source).toContain('text-4xl font-medium tracking-tight text-slate-950 sm:text-5xl');
    expect(source).toContain('flex flex-col gap-4');
    expect(source).toContain('aspect-square');
    expect(source).toContain('grid grid-cols-1 gap-x-6 gap-y-12 sm:grid-cols-2 xl:grid-cols-3');
    expect(source).toContain('absolute inset-x-0 top-0 aspect-square rounded-md bg-slate-100');
    expect(source).toContain('block w-full pt-4');
    expect(source).toContain('text-[1.35rem] font-medium leading-[1.14] tracking-tight');
    expect(source).toContain('flex flex-wrap items-center gap-x-3 gap-y-1 text-sm');
    expect(source).not.toContain('sm:grid-cols-[220px_minmax(0,1fr)]');
    expect(source).not.toContain('sortOrder');
    expect(source).not.toContain('viewMode');
    expect(source).not.toContain('Sırala');
    expect(source).not.toContain('name="mediaView"');
    expect(source).not.toContain('value="grid"');
    expect(source).not.toContain('value="list"');
    expect(source).not.toContain('border-b border-slate-200 py-8');
    expect(source).not.toContain('md:flex-row md:items-center');
    expect(source).not.toContain('md:basis-[17rem] md:shrink-0');
    expect(source).not.toContain('h-20 w-20');
    expect(source).not.toContain('md:h-24 md:w-24');
    expect(source).not.toContain('md:pl-6');
    expect(source).toContain('empty state');
    expect(source).not.toContain('Subscribe to our Newsletter');
    expect(source).not.toContain('Qualy Team');
    expect(source).not.toContain('Qualy Ekibi');
    expect(source).not.toContain('Shared article');
    expect(source).not.toContain('Ortak yayin');
    expect(source).not.toContain('latestPosts');
    expect(source).not.toContain('heroPost');
    expect(source).not.toContain('latestArticles');
    expect(source).not.toContain('recommendedPosts');
    expect(source).not.toContain('categorySections');
    expect(source).not.toContain('blog-section-');
    expect(source).not.toContain('Yazıyı oku');
    expect(source).toContain('BlogIndexPage');
  });
});
